---
- name: Revoke certificates
  when:
    - certbot_server | length > 0
  become: true
  ansible.builtin.command:
    cmd: >
      certbot revoke 
        --server {{ certbot_server }}
        --cert-name {{ item }}
        --reason unspecified
        --delete-after-revoke
    removes: "/etc/letsencrypt/live/{{ item }}"
  loop: "{{ certbot_domains }}"

- name: Remove cron for renewing certs
  become: true
  ansible.builtin.cron:
    name: certbot-renew
    state: absent
