---
- name: Request certificates
  when:
    - certbot_email | length > 0
    - certbot_server | length > 0
    - certbot_eab_kid | length > 0
    - certbot_eab_hmac_key | length > 0
  become: true
  ansible.builtin.command:
    cmd: >
      certbot certonly 
        --standalone
        --non-interactive
        --agree-tos
        --email {{ certbot_email }}
        --server {{ certbot_server }}
        --eab-kid {{ certbot_eab_kid }}
        --eab-hmac-key {{ certbot_eab_hmac_key }}
        --domain {{ item }}
        --cert-name {{ item }}
        --keep-until-expiring
    creates: "/etc/letsencrypt/live/{{ item }}"
  loop: "{{ certbot_domains }}"

- name: Add post hook for renewing certs
  become: true
  ansible.builtin.lineinfile:
    path: /etc/letsencrypt/renewal/{{ item }}.conf
    search_string: post_hook
    line: "post_hook = {{ certbot_post_hook }}"
    state: present
  when:
    - certbot_post_hook is defined
    - certbot_post_hook | length > 0
  loop: "{{ certbot_domains }}"
