---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ certbot_autoremove }}"
    purge: "{{ certbot_purge }}"
    state: absent
  loop: "{{ certbot_packages }}"
